// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukWN2eiAvFe-HP7t55EdNoQEJvoJoWBY',
    appId: '1:11453073530:web:4b99a7f14a6035193bd3c3',
    messagingSenderId: '11453073530',
    projectId: 'urplug-ade39',
    authDomain: 'urplug-ade39.firebaseapp.com',
    storageBucket: 'urplug-ade39.firebasestorage.app',
    measurementId: 'G-7LK01BCW2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Dt-3_NyeHIkzew1jbB2wmh8KhXTfOqM',
    appId: '1:11453073530:android:4466de2b64375eea3bd3c3',
    messagingSenderId: '11453073530',
    projectId: 'urplug-ade39',
    storageBucket: 'urplug-ade39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWjEx98zWGlNiZkqipXaITquPhyhnVWI',
    appId: '1:11453073530:ios:4ec0d16667f29a383bd3c3',
    messagingSenderId: '11453073530',
    projectId: 'urplug-ade39',
    storageBucket: 'urplug-ade39.firebasestorage.app',
    iosBundleId: 'com.example.urPlug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiWjEx98zWGlNiZkqipXaITquPhyhnVWI',
    appId: '1:11453073530:ios:4ec0d16667f29a383bd3c3',
    messagingSenderId: '11453073530',
    projectId: 'urplug-ade39',
    storageBucket: 'urplug-ade39.firebasestorage.app',
    iosBundleId: 'com.example.urPlug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukWN2eiAvFe-HP7t55EdNoQEJvoJoWBY',
    appId: '1:11453073530:web:a3f62c029ffd89f33bd3c3',
    messagingSenderId: '11453073530',
    projectId: 'urplug-ade39',
    authDomain: 'urplug-ade39.firebaseapp.com',
    storageBucket: 'urplug-ade39.firebasestorage.app',
    measurementId: 'G-5VPM5QFCLV',
  );
}
