final Map<String, String> districtSubRegion = {
  'abim': 'karamoja', 'adjumani': 'west nile', 'agago': 'acholi',
  'alebtong': 'lango', 'amolatar': 'lango', 'amudat': 'karamoja',
  'amuria': 'teso', 'amuru': 'acholi', 'apac': 'lango',
  'arua': 'west nile', 'budaka': 'bukedi', 'bududa': 'bugisu & sebei',
  'bugiri': 'busoga', 'bugweri': 'busoga', 'buhweju': 'ankole',
  'buikwe': 'kampala metropolitan area', 'bukedea': 'teso',
  'bukomansimbi': 'south buganda', 'bukwo': 'bugisu & sebei',
  'bulambuli': 'bugisu & sebei', 'buliisa': 'bunyoro',
  'bundibugyo': 'toro', 'bunyangabu': 'toro', 'bushenyi': 'ankole',
  'busia': 'bukedi', 'butaleja': 'bukedi', 'butambala': 'south buganda',
  'butebo': 'bukedi', 'buvuma': 'kampala metropolitan area',
  'buyende': 'busoga', 'dokolo': 'lango', 'gomba': 'south buganda',
  'gulu': 'acholi', 'hoima': 'bunyoro', 'ibanda': 'ankole',
  'iganga': 'busoga', 'isingiro': 'ankole', 'jinja': 'busoga',
  'kaabong': 'karamoja', 'kabale': 'kigezi', 'kabarole': 'toro',
  'kaberamaido': 'teso', 'kagadi': 'bunyoro', 'kakumiro': 'bunyoro',
  'kalaki': 'teso', 'kalangala': 'south buganda', 'kaliro': 'busoga',
  'kalungu': 'south buganda', 'kampala': 'kampala metropolitan area',
  'kamuli': 'busoga', 'kamwenge': 'toro', 'kanungu': 'kigezi',
  'kapchorwa': 'bugisu & sebei', 'kapelebyong': 'teso',
  'karenga': 'karamoja', 'kasanda': 'north buganda', 'kasese': 'toro',
  'katakwi': 'teso', 'kayunga': 'north buganda', 'kazo': 'ankole',
  'kibaale': 'bunyoro', 'kiboga': 'north buganda', 'kibuku': 'bukedi',
  'kikuube': 'bunyoro', 'kiruhura': 'ankole', 'kiryandongo': 'bunyoro',
  'kisoro': 'kigezi', 'kitagwenda': 'toro', 'kitgum': 'acholi',
  'koboko': 'west nile', 'kole': 'lango', 'kotido': 'karamoja',
  'kumi': 'teso', 'kwania': 'lango', 'kween': 'bugisu & sebei',
  'kyankwanzi': 'north buganda', 'kyegegwa': 'toro', 'kyenjojo': 'toro',
  'kyotera': 'south buganda', 'lamwo': 'acholi', 'lira': 'lango',
  'luuka': 'busoga', 'luwero': 'north buganda', 'lwengo': 'south buganda',
  'lyantonde': 'south buganda', 'madi-okollo': 'west nile',
  'manafwa': 'bugisu & sebei', 'maracha': 'west nile',
  'masaka': 'south buganda', 'masindi': 'bunyoro', 'mayuge': 'busoga',
  'mbale': 'bugisu & sebei', 'mbarara': 'ankole', 'mitooma': 'ankole',
  'mityana': 'north buganda', 'moroto': 'karamoja', 'moyo': 'west nile',
  'mpigi': 'south buganda', 'mubende': 'north buganda',
  'mukono': 'kampala metropolitan area', 'nabilatuk': 'karamoja',
  'nakapiripirit': 'karamoja', 'nakaseke': 'north buganda',
  'nakasongola': 'north buganda', 'namayingo': 'busoga',
  'namisindwa': 'bugisu & sebei', 'namutumba': 'busoga',
  'napak': 'karamoja', 'nebbi': 'west nile', 'ngora': 'teso',
  'ntoroko': 'toro', 'ntungamo': 'ankole', 'nwoya': 'acholi',
  'obongi': 'west nile', 'omoro': 'acholi', 'otuke': 'lango',
  'oyam': 'lango', 'pader': 'acholi', 'pakwach': 'west nile',
  'pallisa': 'bukedi', 'rakai': 'south buganda', 'rubanda': 'kigezi',
  'rubirizi': 'ankole', 'rukiga': 'kigezi', 'rukungiri': 'kigezi',
  'rwampara': 'ankole', 'serere': 'teso', 'sheema': 'ankole',
  'sironko': 'bugisu & sebei', 'soroti': 'teso', 'ssembabule': 'south buganda',
  'terego': 'west nile', 'tororo': 'bukedi',
  'wakiso': 'kampala metropolitan area', 'yumbe': 'west nile',
  'zombo': 'west nile',
};

String? subRegionOf(String district) {
  return districtSubRegion[district.trim().toLowerCase()];
}